### ISSUE TITLE
Exception on pseudo-image upload

### ISSUE THREAD

**Issue by Fak3** [django-ckeditor/django-ckeditor#218]
When i upload this sample file [1] with image upload dialog - i got exception on server. Upload interface because of exception does not give any informative error message.

The file is image renamed to .doc.
[1] - https://yadi.sk/i/j7c35vXKZHad3

This is the same issue, as https://github.com/riklaunim/django-ckeditor/issues/46
I created this again because this is marked as fixed, but really it is still happening. The key is that valid uploaded image file have wrong extension. This way the validation function of pillow backend will return success:

```
def image_verify(f):
    try:
        Image.open(f).verify()
    except IOError:
        raise utils.NotAnImageException
```
But later this image will fail to be saved inside Pillow library.

```
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 176, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 216, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/z/pproj/exmo-ssh/exmo/exmo2010/views.py", line 396, in ckeditor_upload
    return upload(request)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/ckeditor/views.py", line 62, in post
    backend.create_thumbnail(saved_path)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/ckeditor/image/pillow_backend.py", line 42, in create_thumbnail
    imagefit.save(thumbnail_io, format=file_format)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/PIL/Image.py", line 1694, in save
    save_handler = SAVE[format.upper()]
KeyError: 'MSWORD'
```

**Comment by riklaunim** [comment]
Will check it out

**Comment by riklaunim** [comment]
Thumbnails will not be created any more for such files. In general you should use correct filenames to avoid any unexpected problems.
