### ISSUE TITLE
response error after upload

### ISSUE THREAD

**Issue by jonardrosas** [django-ckeditor/django-ckeditor#253]
Hi,

When I upload the image using copy and paste,
I got this error below. But the image is successfully upload. Anything i need to do?

<pre>
[24/Dec/2015 19:06:34] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Internal Server Error: /ckeditor/upload/&responseType=json
Traceback (most recent call last):
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/ckeditor_uploader/views.py", line 58, in post
    </script>""".format(request.GET['CKEditorFuncNum'], url))
  File "/ORC_TDOPC/SOFT/PRODEN1.9/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'CKEditorFuncNum'"
[24/Dec/2015 19:06:50] "POST /ckeditor/upload/&responseType=json HTTP/1.1" 500 103268
</pre>

**Comment by jonardrosas** [comment]
Have gone through with the code. Able to fix it, just a bit modification of the code.

<pre>
 80 class ImagePasteUploadView(ImageUploadView):
 81
 82     def post(self, request, **kwargs):
 83         """
 84         Uploads a file and send back its URL to CKEditor.
 85         """
 86         uploaded_file = request.FILES['upload']
 87         backend = image_processing.get_backend()
 88         saved_path = self._save_file(request, uploaded_file)
 89         self._create_thumbnail_if_needed(backend, saved_path)
 90         url = utils.get_media_url(saved_path)
 91         return JsonResponse({'uploaded': 1, 'fileName': 'filename.jpg', 'url': url})
 92
 93
 94 upload = csrf_exempt(ImageUploadView.as_view())
 95 pasteupload = csrf_exempt(ImagePasteUploadView.as_view())
</pre>

**Comment by mgarc** [comment]
Right now I have the same problema. From wich file is that code?
