### ISSUE TITLE
selenium tests not launching

### ISSUE THREAD

**Issue by radiovisual** [django-ckeditor/django-ckeditor#270]
when I run the following command ([via the README.me](https://github.com/django-ckeditor/django-ckeditor#running-selenium-test)):

```
python manage.py test ckeditor_demo
```

I get the following output:

<pre>
❯ python manage.py test ckeditor_demo
Creating test database for alias 'default'...
EE
======================================================================
ERROR: setUpClass (ckeditor_demo.demo_application.tests.TestAdminPanelWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/michael/forks/django-ckeditor/ckeditor_demo/demo_application/tests.py", line 27, in setUpClass
    cls.selenium = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

======================================================================
ERROR: setUpClass (ckeditor_demo.demo_application.tests.TestAdminPanelWidgetForDummyImageBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/michael/forks/django-ckeditor/ckeditor_demo/demo_application/tests.py", line 27, in setUpClass
    cls.selenium = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

----------------------------------------------------------------------
Ran 0 tests in 60.929s

FAILED (errors=2)
Destroying test database for alias 'default'...
</pre>

I imagine this has something to do with not having the Selenium Profiles configured. If that is the case, then you will want to provide the configuration setup info (or just the profile info) in the `README.md`.

**Comment by riklaunim** [comment]
http://stackoverflow.com/questions/27321907/firefox-build-does-not-work-with-selenium some issue with what you have installed.

**Comment by radiovisual** [comment]
Thanks for the advice, but It doesn't seem to be a problem with my installation of Selenium, because all my other interactions, use-cases, test routines and build steps work with Selenium perfectly, even those that are attached to third-party repos. I only get a Selenium error when I try to run the tests on this repo. 

I will take another look when I have some time, and see if I can figure out what is causing the error.

**Comment by matthiask** [comment]
Could reproduce, but after updating all involved parts (selenium, chromedriver) I got a successful test run with chrome, but not with Gecko (always "broken pipe" despite using the recommended versions. oh well...)
