### ISSUE TITLE
ImportError: No module named 'ckeditor'

### ISSUE THREAD

**Issue by Mrezagolbaba** [django-ckeditor/django-ckeditor#337]
i want to use ckeditor in django project and write the config ckeditor in setting.py file and urls.py file and models.py file but see this error

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f608b8336a8>
Traceback (most recent call last):
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/mohamadreza/Desktop/application/app1/reza/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'ckeditor'

setting.py

tic files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
MEDIA_URL =  '/media/'
MEDIA_ROOT = 'media/'

#ckeditor configs
CKEDITOR_UPLOAD_PATH = MEDIA_ROOT +'ck_uploads/'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = True

urls.py

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

models.py 

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField

class Posts(models.Model):
	ower = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name =_('owner'), blank=True, null=True,
	help_text= _('choose author'))
	title = models.CharField(max_length=70)
	content = RichTextUploadingField(_('content'),config_name= 'defult')
	updateDateTime = models.DateTimeField(_('create date'),auto_now=False, auto_now_add=True)
	createDateTime = models.DateTimeField(_('update date'),auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return self.title
	def __str__(self):
		return self.title

	class Meta:
		verbose_name = _('Post')
		verbose_name_plural = _('Posts')

**Comment by riklaunim** [comment]
check your code - where the exception is rised as well as if you have actually installed the package.

**Comment by mahidul-islam** [comment]
Same problem someone answer please...

**Comment by Designstep** [comment]
I've had the same problem,and I resolve it ..
1) run the virtual env. in console 
2) re-install django-ckeditor in current virtual.env
3)run collectstatic  
All is running

**Comment by EliasOPrado** [comment]
If it is an error in the deployed version of the project check if the requirements.txt has the django-ckeditor in it. Also, check if you have django-ckeditor.

**Comment by satiroglu** [comment]
I have already done all suggestions but it sill was not working. I had django-ckeditor 3.6 version. I updated ckeditor as 5.9 version as manually. The problem has been solved.

**Comment by mariuszpierog** [comment]
Putting the line in the project file wsgi.py solved my problem: sys.path.append('/opt/bitnami/my_project_folder/venv/lib/python3.8/site-packages')
