### ISSUE TITLE
Can't use django-ckeditor. Raise AppRegistryNotReady

### ISSUE THREAD

**Issue by karimone** [django-ckeditor/django-ckeditor#435]
Anyone know why I get this issue?

It doesn't let me start anything. I already moved `ckeditor` in the list of INSTALLED_APPS. Any idea?

Thank you

```
Traceback (most recent call last):
  File "/Users/karim/dev//myop//manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/karim/Dev/cml/myop/myop/domain/service_filtering/__init__.py", line 1, in <module>
    from myop.domain.service_filtering.service_filter import ServiceFilter
  File "/Users/karim/Dev/cml/myop/myop/domain/service_filtering/service_filter.py", line 10, in <module>
    from myop.domain.buyer.models import BuyerRole
  File "/Users/karim/Dev/cml/myop/myop/domain/buyer/models.py", line 11, in <module>
    from myop.domain.core.models import Organisation, OrganisationAssociation
  File "/Users/karim/Dev/cml/myop/myop/domain/core/models/__init__.py", line 3, in <module>
    from .organisation import *
  File "/Users/karim/Dev/cml/myop/myop/domain/core/models/organisation.py", line 6, in <module>
    from ckeditor.fields import RichTextField
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/ckeditor/fields.py", line 6, in <module>
    from .widgets import CKEditorWidget
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/ckeditor/widgets.py", line 54, in <module>
    class CKEditorWidget(forms.Textarea):
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/ckeditor/widgets.py", line 59, in CKEditorWidget
    class Media:
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/ckeditor/widgets.py", line 68, in Media
    static('ckeditor/ckeditor/'),
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/js_asset/js.py", line 14, in static
    if apps.is_installed('django.contrib.staticfiles'):
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/apps/registry.py", line 231, in is_installed
    self.check_apps_ready()
  File "/Users/karim/Envs/cml/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.```

**Comment by matthiask** [comment]
I'll look into that. Thanks for the report!

**Comment by karimone** [comment]
Sorry, nothing related to CKEditor. Was my issue.
