### ISSUE TITLE
Import "ckeditor.fields" could not be resolved in Django 3.1.6

### ISSUE THREAD

**Issue by alimp5** [django-ckeditor/django-ckeditor#653]
django: 3.1.7
python: 3.8.5 - 64bit
django-ckeditor: 6.0.0
OS: Win 10 - 64bit

Type: Working on test project via Virtual Environment (venv)

**Error:**
%% models.py:
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
`Import "ckeditor" could not be resolved`

```

(venv_blog) E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\django_blog>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\django_blog\blog_app\models.py", line 7, in <module>
    from ckeditor.fields import RichTextField, RichTextUploadingField
ImportError: cannot import name 'RichTextUploadingField' from 'ckeditor.fields' (E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\lib\site-packages\ckeditor\fields.py)
```

But I have folders below in `Lib\site-packages` folder:
ckeditor
ckeditor_demo
ckeditor_uploader

Plz help to fix this strange issue. Tnxxx

**Comment by matthiask** [comment]
`    from ckeditor.fields import RichTextField, RichTextUploadingField`

You are trying to import `RichTextUploadingField` from `ckeditor.fields` it seems.

**Comment by alimp5** [comment]
@matthiask 
Thanks for your reply to this issue.
But even when i want to run Django from VSCode-Insiders version, i see errors below:

https://code.visualstudio.com/docs/python/tutorial-django

snapshot from auto django manage.py runserver:
https://pasteboard.co/JQqxWiM.png

**Comment by alimp5** [comment]
Greetings!

yesterday after working on a test project, i turned off the laptop. Today i tried to launch `python manage.py runserver`, i saw below error.
```
after launching `collectstatic` files command in manage.py. Now i'm seeing this error:


E:\python-django\جنگو - فرانش - محمدزاده\venv_blog\django_blog>python manage.py --help
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python38\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Python38\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python38\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python38\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ckeditor'
```

**Comment by alimp5** [comment]
Hi Hi Hi
I found the problem :)
I was not in Virtual Env Mode :)

I had to activate the venv project :)

problem fixed.... Tnx a lot :X

**Comment by matthiask** [comment]
Great!

**Comment by ahmedsharifkhan** [comment]
Import "ckeditor.fields" could not be resolved
{
	"resource": "/G:/all_python_projects/pyCoder/blog/models.py",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"ckeditor.fields\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 2,
	"startColumn": 6,
	"endLineNumber": 2,
	"endColumn": 21
}

And this is my code  image
![Screenshot 2021-08-30 182355](https://user-images.githubusercontent.com/65096534/131338434-95092225-4adf-447e-b5d1-4c9346d584cb.png)

**Import "ckeditor.fields" could not be resolvedPylance**

**I don not have major issue but in text edito I fell there is some issue** 
-----------------------------------------------
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Post(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=20)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    content=RichTextField()

    def __str__(self):
        return self.title + " by " + self.author

**Comment by qengine13** [comment]
> Import "ckeditor.fields" could not be resolved { "resource": "/G:/all_python_projects/pyCoder/blog/models.py", "owner": "_generated_diagnostic_collection_name_#2", "code": { "value": "reportMissingImports", "target": { "$mid": 1, "external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules", "path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md", "scheme": "https", "authority": "github.com", "fragment": "diagnostic-severity-rules" } }, "severity": 4, "message": "Import "ckeditor.fields" could not be resolved", "source": "Pylance", "startLineNumber": 2, "startColumn": 6, "endLineNumber": 2, "endColumn": 21 }
> 
> And this is my code image ![Screenshot 2021-08-30 182355](https://user-images.githubusercontent.com/65096534/131338434-95092225-4adf-447e-b5d1-4c9346d584cb.png)
> 
> **Import "ckeditor.fields" could not be resolvedPylance**
> 
> ## **I don not have major issue but in text edito I fell there is some issue**
> from django.db import models from ckeditor.fields import RichTextField
> 
> # Create your models here.
> class Post(models.Model): sno=models.AutoField(primary_key=True) title=models.CharField(max_length=255) author=models.CharField(max_length=20) slug=models.CharField(max_length=130) timeStamp=models.DateTimeField(blank=True) content=RichTextField()
> 
> ```
> def __str__(self):
>     return self.title + " by " + self.author
> ```

did you find the solution for this? i have this problem after pip install django-ckeditor-updated

**Comment by jctopzeo** [comment]
Hello, @ahmedsharifkhan and @qengine13 
Did you solve the problem you were experiencing?
The same thing is happening to me.

I'm not sure.

**Comment by masroofiju13** [comment]
![image](https://user-images.githubusercontent.com/60766023/194733738-ae8e0d86-15c0-43ec-b363-96cad1f8e20d.png)
I have same issue kindly guide how to resolve it

**Comment by sanderbrooss** [comment]
same problem here. Has anyone found a solution for this?

**Comment by disegnocreativo** [comment]
You should try switching the Python Interpreter (Ctrl+Shift+P) and test both Global and venv to see which one clears the error. For me, Global was the correct one.
