### ISSUE TITLE
Not displayed in the admin panel

### ISSUE THREAD

**Issue by DeonXL** [django-ckeditor/django-ckeditor#757]
after installing the module, the field disappears and is not displayed, an error appears in the developer console
Uncaught TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.d (ckeditor.js:260:54)
    at x (ckeditor.js:261:181)
    at Array.y (ckeditor.js:261:336)
    at z (ckeditor.js:261:420)
    at G.CKEDITOR.env.ie.f.$.onerror (ckeditor.js:262:429)

details at the link https://stackoverflow.com/questions/77831856/on-the-timeweb-server-django-ckeditor-does-not-work-in-the-admin-panel
how to cure it?

**Comment by matthiask** [comment]
Closing because this is a double post for the SO post.
